Update visualizer.py
RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.
Fixed the above error by adding detach.